# Generated by Django 2.0.7 on 2018-07-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20180712_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsrecord',
            old_name='image1',
            new_name='file1',
        ),
        migrations.RenameField(
            model_name='newsrecord',
            old_name='image2',
            new_name='file2',
        ),
        migrations.RenameField(
            model_name='newsrecord',
            old_name='image3',
            new_name='file3',
        ),
    ]
