# Generated by Django 2.0.6 on 2018-06-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackrecord',
            old_name='pronlem',
            new_name='problem',
        ),
    ]
