# Generated by Django 2.0.7 on 2018-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20180618_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrecord',
            name='user_email',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackrecord',
            name='user_name',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
    ]
