# Generated by Django 2.0.7 on 2018-07-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_auto_20180722_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackUserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
