# Generated by Django 2.0.6 on 2018-07-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminPanelUsers',
            new_name='AdminPanelUser',
        ),
    ]
