# Generated by Django 2.0.6 on 2018-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_auto_20180711_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpaneluser',
            name='password',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
