# Generated by Django 2.0.7 on 2018-07-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_adminpaneluser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanelAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField()),
                ('ad_text', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_stop', models.DateTimeField()),
            ],
        ),
    ]
