# Generated by Django 2.0.6 on 2018-07-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Error505Record',
            new_name='Error500Record',
        ),
    ]
